### ISSUE TITLE
AppImage/Snap/Flatpack

### ISSUE THREAD

**Issue by GustavoKatel** [Eugeny/tabby#1869]
Hi! Great work on this!

Is it possible to bundle in one of AppImage/Snap/Flatpack?

I use Solus linux and it does not have support for .deb.

Best regards

**Comment by textshell** [comment]
Just a drive-by if anyone wants to have a starting point to add a general purpose flatpak.
I've just added terminus to a project to keep terminals for testing applications around. This is not intended for actual daily usage (e.g. always uses pinned versions, no intend for any security support etc). But it might be helpful as a starting point for a upstream general purpose flatpak. The 3 big stumbling points have been, `/etc/shells`, sandbox and it needs udev installed inside of the flatpak (done that using the gnome sdk instead of the freedesktop sdk)
https://github.com/textshell/flatpak-terminal-zoo/tree/master/terminus

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
Flatpak is very important for me, so please consider this.

**Comment by CodeCubeNeo** [comment]
I agree, a flatpak would be awesome and would help spread the application. I think this should be reopened.

**Comment by BadCo-NZ** [comment]
As a user of an immutable OS that requires flatpaks, I would also like to see a flatpak version :)

**Comment by jing2uo** [comment]
For anyone still using Tabby and wanting a Flatpak install — I've packaged one via [FlatPark](https://flatpark.org/):

https://flatpark.org/apps/org.tabby.Tabby/

```
flatpak --user remote-add --if-not-exists flatpark https://dl.flatpark.org/flatpark.flatpakrepo
flatpak --user install flatpark org.tabby.Tabby
```

It wraps Tabby's official .deb release as Flatpak extra-data — each install pulls the binary straight from the GitHub release, unmodified. You can review the manifest, install script and sandbox permissions to confirm there's no hackery: [registry/org.tabby.Tabby](https://github.com/jing2uo/flatpark/tree/main/registry/org.tabby.Tabby). 🐧
