### ISSUE TITLE
upgrade not working

### ISSUE THREAD

**Issue by mmalzkuhn** [Eugeny/tabby#1951]
Version: 1.0.97
Platform: win32 10.0.18362
Plugins: none
I get an icon saying an upgrade is available.  I click it and things seem to start normally including shutting down the terminus that is running.  But then nothing happens.  It does not restart.  Several minutes later I started terminus again and it is still on 1.0.97.

**Comment by delroh** [comment]
This has been happening for me since I started using terminus months ago. The solution is to not use the upgrade option from the running terminus app.

How to trigger the issue:
1. Run terminus, click icon saying an upgrade is available.
2. The installer will start, then a prompt will  ask to terminate the running terminus app so it can proceed with installation. Now here is the issue: the prompt asking to terminate the running app ends up killing itself. Nothing else will happen.

Workaround:
Run the installer separately, as in download the installer and run from the downloaded file instead of using the upgrade option from the terminus app, it will work correctly. It will terminate the running app and not terminating itself (the installer).

**Comment by Onepamopa** [comment]
Plugins install also doesn't work...

**Comment by delroh** [comment]
This is the same issue https://github.com/Eugeny/terminus/issues/1495
