### ISSUE TITLE
Clear screen and scrollbuffer?

### ISSUE THREAD

**Issue by pardeike** [Eugeny/tabby#2376]
I'm looking for a terminal that does what my macOS terminal does: Cmd-K (your cmd-L) clears the screen **and** the scrollback. Is this possible with the core application or with a plugin?

**Comment by dmitriy-pritula** [comment]
I will vote for this issue as well.
Many thanks to makers.

**Comment by leegee** [comment]
I bought the potentially free-to-use iTerm2 because the` CMD+K` works so well. 
Now I find myself in the land of Windows 10, at least with Debian/WSL, and Terminus shows massive potential but it does get confused when the 'clear screen' feature is used - much like the new Windows terminal as used in VSC, the screen and scrollback buffer clear, but often (95%) after clearing the screen and typing a line, the cursor skips to the bottom of the screen.
(Sometimes the cursor skips up a line but that's unrelated, I guess)

**Comment by pardeike** [comment]
Bump

**Comment by leegee** [comment]
Still a problem.

**Comment by leegee** [comment]
Still an issue and I no longer use the product as a consequence.

**Comment by nicbet** [comment]
Just came by the GitHub repo today seeing if this has been reported or fixed yet. Experiencing the same issue, clear screen clears partially and on next command output jumps to bottom of terminal. Loving Tabby so far but this is one annoying bug for sure ;-0

Tabby 1.0.158
Windows 10 20H1
Latest oh-my-zsh 29b5c182

**Comment by MikhailKlemin** [comment]
Yeah, have to try other apps but Tabby is really cool! But this is just annoying, I have open new tab each time  I need my scroll buff clean :-(

**Comment by Eugeny** [comment]
I might be misunderstanding it, but have you tried the `Clear terminal` (`clear`) hotkey that Tabby provides? It's Cmd-K on Mac and unset on Windows by default and clears both the scrollback and the buffer.

**Comment by MikhailKlemin** [comment]
> 

No,  it was me, who was misunderstanding.
I used to issue `reset` in terminal under ubuntu and it was clearing all fine (include scroll buffer). Now,  I bound `clear` to a key, and it's definitely works, thanks a lot!
