### ISSUE TITLE
Validate host key fingerprints

### ISSUE THREAD

**Issue by SpokeyTheUser** [Eugeny/tabby#2419]
![Capturar](https://user-images.githubusercontent.com/63773599/79422680-37c9c680-7fb5-11ea-9a4a-8296341238d6.PNG)
How can i disable this from appearing

**Comment by gremo** [comment]
Asking the same question.

**Comment by Beefster09** [comment]
I'm not sure it's a good idea to hide that. In theory, it gives you a chance to verify the identity of the server. If that is ever different, you have reason to be worried.

Probably should be an option, but still. It's only two lines and it's not a big deal to ignore.

**Comment by gremo** [comment]
>  If that is ever different, you have reason to be worried.

In your opinion, I'm going to remember the fingerprint of my servers? 😄 

C'mon... Terminus should warn the user if fingerprint changes between the one stored, not bother about the host fingerprint all the time, IMHO.

**Comment by BigStar0916** [comment]
> I'm not sure it's a good idea to hide that. In theory, it gives you a chance to verify the identity of the server. If that is ever different, you have reason to be worried.
> 
> Probably should be an option, but still. It's only two lines and it's not a big deal to ignore.

most ssh client will have warning for first login and hostkey changed.I think this is the most important to avoid man in the middle attck.but tabby no any warning.i do not thinks it is a good idea to use human eyes to check fingerprint for every time every login.so i uninstall tabby to use putty and winscp. for android . i also uninstall file manager  which support sftp because all these sftp file manager no warning for first nogin to check fingerprint. i use anxray/sagernet to connect to ssh server, then can connect sftp via private ip, it works look like vpn clients.because this 2 tools can add host key's  pubkey to verify and avoid man in the middle attack.I will find anxray/sagernet is not professional ssh client but do the perfect things.
