### ISSUE TITLE
Hide Terminus when click the close button

### ISSUE THREAD

**Issue by sweetliquid** [Eugeny/tabby#2514]
Version: 1.0.107
Platform: win32 10.0.19041
Plugins: clickable-links

Can you add a setting to hide Terminus when click the close button instead of directly closing it? Please ~

**Comment by manohar-voggu** [comment]
@Eugeny 
In Mac OS, When Terminus App icon in the Dock is clicked, the app opens (As evident from 'Terminus' appearing in top menu bar), but no window shows up. On clicking the app icon again, window opens up.

This is inconvenient as two clicks are needed to open up terminal. 
To add to this, when the close button is clicked, the app gets "Quit" instead of "Hide".
If that wasn't the case, it would have needed 2 clicks for the first time, and just one click for the subsequent openings.

Modifications needed:
1) Hide App instead of Quit, when close button is clicked
2) Open window whenever app is opened

First Click:
![Screenshot 2020-05-13 at 1 12 43 PM](https://user-images.githubusercontent.com/50870617/81785933-9898e000-951c-11ea-8cc7-ca9cb2d8f327.png)

Second Click:
![Screenshot 2020-05-13 at 1 13 08 PM](https://user-images.githubusercontent.com/50870617/81785952-9f275780-951c-11ea-9ddb-c5d6b11481d3.png)

**Comment by manohar-voggu** [comment]
The issue I described above is similar to https://discussions.apple.com/thread/250728250

PS:
I'm on Version 1.0.111 (1.0.111) of Terminus.
I'm aware of "Hide Terminus" option in the menu bar. I hope that functionality will be made the default for the close button.

![Screenshot 2020-05-13 at 1 29 05 PM](https://user-images.githubusercontent.com/50870617/81786955-fa0d7e80-951d-11ea-80dd-adafe9b37626.png)
