### ISSUE TITLE
X11 Forwarding Fail

### ISSUE THREAD

**Issue by rakeshnattoji** [Eugeny/tabby#2654]
I am using https://x.cygwin.com/ on Windows 10 as X Server

With X11 Forwarding enabled, I get the following error message
_Invalid MIT-MAGIC-COOKIE-1 keyUnable to init server: Could not connect: Connection refused_

This error was fixed in PuTTY by setting location of X Authority file.
Please support similar option in terminus.

Thanks,
Rakesh
![putty](https://user-images.githubusercontent.com/66336693/83574872-327ff700-a4e3-11ea-965f-10fd5b7f072e.PNG)

**Comment by rakeshnattoji** [comment]
@cibrhusk 

Your solution is for switching between X11 sessions. This is not the problem I was describing. 
_"Your most likely using cygwint openssh to connect to your remote machine"_ I am not.

Some more details.

Server
OS: Ubuntu 18.04 LTS
SSH Server: OpenSSH_7.6p1 Ubuntu-4ubuntu0.3, OpenSSL 1.0.2n  7 Dec 2017

Client
X Server: Cygwin/X (X server 1.20 and X.Org X11 Release 7.7)

SSH Client: Putty 0.73  **without** cilent .Xauthority file location set -> _Invalid MIT-MAGIC-COOKIE-1 keyUnable to init server: Could not connect: Connection refused_
SSH Client: Putty 0.73  **with** cilent .Xauthority file location set -> _Works as expected_

SSH Client: Eugeny terminus -> _Invalid MIT-MAGIC-COOKIE-1 keyUnable to init server: Could not connect: Connection refused_

**Comment by cibrhusk** [comment]
Your right, my bad. 

I second this issue with the buildin ssh client, verbose logging would be great for further investigation. My error with the latest is:

SSH   X  Could not connect to the X server :6000: Error: connect ECONNREFUSED 127.0.0.1:6000
xterm: Xt error: Can't open display: localhost:11.0

Same issue does not exist when using cygwin openssh client insude terminus.

N.b.: A gui wrapper for OpenSSH instead of maintaining your own client with all its riscs and support issues would imho be much more preferable.
