### ISSUE TITLE
Nano editor UI problems

### ISSUE THREAD

**Issue by UAnton** [Eugeny/tabby#2888]
Version: 1.0.116
Platform: darwin 20.0.0
Plugins: none

Symbols with hints at the bottom of the nano editor window are not displayed.

[In Terminal app](http://i.piccy.info/i9/c23c85a523a18064fa84fcfdabf3e449/1597161021/25927/1391702/Snymok_ekrana_2020_08_11_v_18_48_48.jpg)
[In Terminus app](http://i.piccy.info/i9/7ddec9855e16e5d4ae8e846b85ed08bc/1597161147/26145/1391702/Snymok_ekrana_2020_08_11_v_18_53_44.jpg)

**Comment by docsav** [comment]
I had a similar problem with Micro editor, but it turned out to be related to my monochrome color scheme. It took some experimenting to find which color values corresponded to the letters in the highlighted area, and make that a darker color. I don't assume that is the case in your situation but it might be worth switching to a different color scheme to check.

**Comment by Eugeny** [comment]
Also, it's a known issue if you're using the xterm-webgl frontend with vibrancy enabled
