### ISSUE TITLE
C-@ and C-Space can't be passed to terminal

### ISSUE THREAD

**Issue by SpadedotS** [Eugeny/tabby#3053]
OS: Windows 10 64bit
Version: Terminus Alpha 1.0.120
I'm using Terminus to connect to server via SSH. When I'm using emacs, I found that some key-pairs can't be passed to the terminal (Like C-@ and C-Space, they're mark-set in emacs). I've cleared hotkeys that conflict with them, but this still didn't help. Is this a bug?
Thank you for your reading! Looking forward to your reply

**Comment by SpadedotS** [comment]
Update: After changing the input method, I found that C-Space is passed to terminal, but the C-@ didn't came effect.

**Comment by ragreenburg** [comment]
Related to this, if you have the GUI version of Emacs open and Terminus open whenever you hit `CTRL+Space` it will jump from Emacs to Terminus which I would greatly appreciate knowing how to get rid of because in Emacs that is how you highlight sections of code. Makes it so every time I need to highlight code I end up closing the terminal until I need it again.

**Comment by Eugeny** [comment]
@ragreenburg Ctrl-Space is the default global hotkey for "Toggle Window", which you can disable in Settings -> Hotkeys.

**Comment by mathslimin** [comment]
If you want to use emacs, settings ctrl-space must unbind
