### ISSUE TITLE
"Bracketed paste" and "Warn on multi-line paste" do not work when I use Shift+Insert to paste

### ISSUE THREAD

**Issue by Elger9** [Eugeny/tabby#3565]
"Bracketed paste" and "Warn on multi-line paste" does not work when I use Shift+Insert to paste.

In the above case, these options behave as if they were disabled.

Out of habit from another program I use Shift+Insert. This combination works even though it is not defined in "HotKeys".

When I define this combination in Hotkeys, the mentioned options work as expected.

**Comment by yphastos** [comment]
Same issue here. 

Being on Windows, I also paste with `Shift+Insert` on terminals since is the most universal shortcut. But Tabby doesn't intercept it well to avoid multi-lines.

I have solved it as @Elger9 suggests, adding `Shift+Insert` as an alias to the `Paste from clipboard` hotkey, but new users may oversee it and wrongly paste multi-line commands.

A temporary solution would precisely be to add the alias by default to the hotkey.
