### ISSUE TITLE
Feature Request: Option to close window when all tabs are closed

### ISSUE THREAD

**Issue by alterae** [Eugeny/tabby#3862]
**Expected Behavior:** When the last tab in a terminal window is closed (IE: through the close tab button or `exit`), the entire window should close as well.  This is standard behavior in most other terminal apps (including Hyper, Windows Terminal, and if I remember correctly the default terminal application on MacOS).

**Actual Behavior:** When the last tab in the window is closed, the window remains open, displaying a screen that shows options already available in the main window toolbar.

I recognize this is an intentional design choice, but it would be very nice and eliminate a great deal of friction if an option were added in the settings menu to enable a more standard window/tab behavior.

**Comment by Xenolphthalein** [comment]
+1 
I would love to see this feature in terminus. It's the only thing that i miss.
A new option in the "Terminal" tab of the settings called "Close terminus if last terminal(<=> tab) is closed" located directly under "Restore terminal tabs on app start".

**Comment by dnut** [comment]
I would love to see this feature implemented. This is a very common use case for me. I'm often just spinning up a terminal for a short task and then closing it with ctrl-d as soon as I'm done. For now I'm sticking with terminator for this purpose because I have to use the mouse to click X to close the window which interrupts my workflow. Also tabby takes too long to start. Not a streamlined entry/exit.
