### ISSUE TITLE
搜狗输入法输入不了中文

### ISSUE THREAD

**Issue by BLACKLOVEBULE** [Eugeny/tabby#4260]
Version: 1.0.148
Platform: win32 10.0.18363
Plugins: none

Sogou input method can't input Chinese

**Comment by z0ow** [comment]
This bug has been reported many times before. Issue #3656 said this problem is often occurs in new versions, and the Microsoft input method (Pinyin) is working well with Tabby. 

To ensure this bug is or is not cause by the Sogou Pinyin, I have tested many other IME like Baidu Pinyin that are different from Microsoft. Sadly the result proves that only the Microsoft input method works well with Tabby.

For the limits of the test environment, the above conclusion is only credible in Windows10 + Tabby + Chinese input methods (exclude the Microsoft Chinese input method). As the common usage scenarios, this bug brings inconveniences to users. It makes Tabby not sharp anymore (could not change directories or open files which contain Chinese in SSH/Terminal via Tabby).

May authors pay a little time to introduce how we can provide more valuable information to make Tabby perfect?

**Comment by BLACKLOVEBULE** [comment]
您好，
&nbsp; &nbsp; &nbsp; &nbsp;我非常喜欢Tabby，即使搜狗输入法输入不了中文，我还是坚持在用，并且也推荐身边的人再用。中国有句古语：“爱之深，责之切”，因为我喜欢Tabby，所以希望它越来越好。若中文字符输入问题能解决，那就很完美了。如果我发现有价值的线索，我会第一时间告知。希望大家一起努力，早日修复这个bug。
&nbsp; &nbsp; &nbsp; &nbsp; 祝：一切顺利！


撒在銀河裡
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Eugeny/tabby"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月28日(星期三) 凌晨0:13
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Eugeny/tabby] 搜狗输入法输入不了中文 (#4260)





 
This bug has been reported many times before. Issue #3656 said this problem is often occurs in new versions, and the Microsoft input method (Pinyin) is working well with Tabby.
 
To ensure this bug is or is not cause by the Sogou Pinyin, I have tested many other IME like Baidu Pinyin that are different from Microsoft. Sadly the result proves that only the Microsoft input method works well with Tabby.
 
For the limits of the test environment, the above conclusion is only credible in Windows10 + Tabby + Chinese input methods (exclude the Microsoft Chinese input method). As the common usage scenarios, this bug brings inconveniences to users. It makes Tabby not sharp anymore (could not change directories or open files which contain Chinese in SSH/Terminal via Tabby).
 
May authors pay a little time to introduce how we can provide more valuable information to make Tabby perfect?

**Comment by wordhui** [comment]
I really can’t use Sogou input method to input Chinese
All versions of tabby from the previous terminus to the current tabby do not support, use Sogou input method to input Chinese

**Comment by LuhengStat** [comment]
The new version is compatible with Sogou now

**Comment by BLACKLOVEBULE** [comment]
I'm very excited to get the news！Tabby is doing better and better, and I'm happy about it. Tabby will become a mainstream tool in the future！I love tabby.




撒在銀河裡
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Eugeny/tabby"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月9日(星期六) 上午10:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Eugeny/tabby] 搜狗输入法输入不了中文 (#4260)





 
The new version is compatible with Sogou now
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by wugeng617** [comment]
1.0.173版本仍然有这个问题，无法输入中文

**Comment by Eugeny** [comment]
@wugeng617 please see https://github.com/Eugeny/tabby/issues/4999#issuecomment-1065959329
