### ISSUE TITLE
Can not drag reorder tabs on Macbook Pro

### ISSUE THREAD

**Issue by wudisheng** [Eugeny/tabby#4324]
Using 1.0.150 (confirmed from 1.0.147 up) on MacOS 11.5.1 (Big Sur), the Tabby window is maximized (but not in fullscreen mode).

The entire Tabby window moves when dragging a tab title, effectively makes it very difficult to reorder tabs, and inconvenient because the Tabby window shifts slightly even with a single click (tap) on the title bar.

This doesn't occur on other tab-enabled applications such as Chrome or Firefox, etc.

One detail is, the tab index and the close button is draggable and can actually be used to reorder tabes, but it requires very accurate cursor positioning.

**Comment by Eugeny** [comment]
Thanks for the report. On macOS, dragging the tab is only possible on the tab index - the glitch which happens when dragging on the tab header body is new due to angular-cdk migration. 

If you feel you'd rather have an option to have the entire tab header draggable, feel free to convert this into an enhancement ticket

**Comment by wudisheng** [comment]
Upgraded to 1.0.152 and the issue is still there --- a single click on the title bar or any tab header (using TouchPad) moves the entire window slightly --- when the entire window is maximized (but not fullscreen), it would be off screen and quite annoying to realign.

Can we add an option to disable window move or so?
