### ISSUE TITLE
High CPU usage  

### ISSUE THREAD

**Issue by wqk151** [Eugeny/tabby#4443]
## 环境
os: Ubuntu20.04
tabby version: 1.0.154

## 1. High CPU usage  
Open a file with Vim, just by moving the cursor ,CPU usage was over 80%  (use `top` )
![captrue](https://user-images.githubusercontent.com/18275602/129880800-767ee356-227f-495d-b39c-4066b63b4b0c.png)
![captrue1](https://user-images.githubusercontent.com/18275602/129880812-df465c93-93a2-422d-a7c0-a2b90564ca4b.png)

## 2.  can not  start after close tabby
If I want to start Tabby again, I need to use `ps` to find the process number and then kill it 。

**Comment by enodr** [comment]
Hi,

I think the same problem plagues Tabby for a long time and several issues have already been opened. I have came to the point where in a day I have to kill Tabby at least once. The issue is really easy to reproduce: cat a large file in a term and boom all your terms are unusable and tabby takes a full CPU core.

There seems to be too much parsing done in one thread, thus making all the other open terminals barely usable and totally unresponsive.

**Comment by wqk151** [comment]
I have five terminals hah， i like Tabby，It's powerful, but consistently low performance from Terminus to Tabby,  because I feel very stuck when writing code，if  can improve its performance, that would be the perfect one
![1](https://user-images.githubusercontent.com/18275602/129995696-1a240d23-3f8b-49c0-96a7-df6c2f367d35.jpg)

**Comment by Eugeny** [comment]
Have you already tried the xterm-webgl frontend? It's way faster.

**Comment by Eugeny** [comment]
The stuck processes issue is a duplicate of #4442

**Comment by enodr** [comment]
Some performance benchmark for comparison (measured time to display output):

tabby: zcat bigfile.gz => about 90 seconds
visual studio code terminal: zcat bigfile.gz => less than 3 seconds

(I bench with visual studio code terminal because it is also based on xterm.js)

**Comment by Eugeny** [comment]
Could you please capture a performance trace when catting a large file? You can do it via Settings -> Application -> Dev tools -> Performance -> Record and then export.

The frontend selector is in Settings -> Terminal - changes only apply to new tabs.

**Comment by enodr** [comment]
I just cat a 1000 line file locally, you can see the CPU is 100% (one core). Seems the culprit is rxjs Subject?

![tabby-trace](https://user-images.githubusercontent.com/10436257/130050219-c09ae5d4-fefa-459e-b41b-bae84317f7d7.png)

[Profile-20210819T120008.json.gz](https://github.com/Eugeny/tabby/files/7013547/Profile-20210819T120008.json.gz)

**Comment by Eugeny** [comment]
Thanks - could you try and see if setting `terminal.detectProgress` = `false` in the config file makes it any faster? RxJS isn't a culprit here - it just happens to be on the hot path - see how its self time is 0.

**Comment by enodr** [comment]
Good shot! That works. Down from 90s to about 12s for a 40k lines file. Not yet as fast as Visual Studio Code terminal (3s) but I guess they aren't doing as much parsing as you do in Tabby.

**Comment by Eugeny** [comment]
I just went down the rabbit hole of profiling and came out with another 3x performance bump - should be in the nightly right now!

**Comment by wqk151** [comment]
-  The problem is still, High CPU utilization,move cursor slow, not smooth in a 23 lines file.
![captrue](https://user-images.githubusercontent.com/18275602/130169443-e9cfd104-3583-4c5c-931a-8a5cd1fab3a4.png)
- config 
![2021-08-20 10-20-47 的屏幕截图](https://user-images.githubusercontent.com/18275602/130169614-3641e020-558d-4d19-8dbe-e632355f55e5.png)

-  Performance analysis
![2021-08-20 10-20-03 的屏幕截图](https://user-images.githubusercontent.com/18275602/130169650-2818a343-4131-4953-a8e4-dd455f29a46c.png)

[Profile-20210820T102016.zip](https://github.com/Eugeny/tabby/files/7018729/Profile-20210820T102016.zip)

**Comment by Eugeny** [comment]
@wqk151 it doesn't look like the trace is from the latest nightly - could you please update?

**Comment by enodr** [comment]
Same test as before: cat a file with 40k lines. With latest nightly build we are down to 7s instead of 12s, so definitively an improvement. 

Also I confirm that now I can CTRL+C a process when the screen is flooding, while before it was not possible as the high CPU usage prevented keys from being registered.

**Comment by wqk151** [comment]
> @wqk151 it doesn't look like the trace is from the latest nightly - could you please update?

It is the latest vaersion, 1.0.155. I have updated it before trace.

**Comment by Eugeny** [comment]
The performance improvements are in the nightly build only yet, which you can get via the "nightly builds" link in the repo readme

**Comment by gitgt** [comment]
Please comment on the performance of the current tabby.
What does terminal.detectProgress = false in the config file do and should it be used?
