### ISSUE TITLE
Most recently used

### ISSUE THREAD

**Issue by tonycody** [Eugeny/tabby#5537]
![image](https://user-images.githubusercontent.com/6773121/150045988-e5529ad3-8538-4aa2-8d64-66701593fed8.png)
Can you put the most recently used order at the top? It's also more reasonable

**Comment by Eugeny** [comment]
Could you please clarify your request? The most recently used profiles are already shown on top in the "Recent" group.

**Comment by G-regL** [comment]
The most recently used profiles are sorted at the top, assuming the group names you have don't start with something that's alphabetically before the word 'Recent' 

I just tested this on 1.0.173.

Having groups called 'Home' and 'Work' puts the Recent connections between the two. If I rename 'Home' to 'zzz-Home' then 'Recent' does in fact appear at the top.

I presume that's caused by the 'Recent' group using the same logic as manually created groups.

Perhaps it's possible to statically place the 'Recent' group at the top of that list, regardless what other group names exist.
