### ISSUE TITLE
login script not executing

### ISSUE THREAD

**Issue by eugenov** [Eugeny/tabby#5786]
Version: 1.0.172
Platform: Windows x64 10.0.22000
Plugins: save-output
Frontend: xterm-webgl

Hello!
It seams that tabby stopped to execute login scripts. Couple of versions ago it was ok with that. Screens:
1
![изображение](https://user-images.githubusercontent.com/61651148/154451540-768113b5-decc-4d50-9e8f-86a7980b5a93.png)
2
![изображение](https://user-images.githubusercontent.com/61651148/154451363-fb158b04-479d-4faf-9ec4-78a54d94b5ea.png)

**Comment by aobataliang** [comment]
yes, it happened to me also with 1.0.172.

**Comment by eugenov** [comment]
With 1.0.173 it seams to work

**Comment by dchevilletRDR** [comment]
I have always the "problem" but, I can give more details.
It comes from the "Reuse sessions for multiple tabs". Some of my SSH session connect first to my VM and then go to remote server. But if I have this option checked and a first tabs open to my VM via SSH, then the next tabs open, don't run the login script, because it's the same connexion.

So I think it's works as designed, just unchecked the "reuse session..." option.
