### ISSUE TITLE
When connecting to a switch, the backspace key cannot take effect directly, you need to press Shift to use it.

### ISSUE THREAD

**Issue by cmmchina** [Eugeny/tabby#5862]
Version: 1.0.173
Platform: macOS x64 21.3.0
Plugins: workspace-manager, title-control, search-in-browser, save-output, quick-cmds, altair
Frontend: xterm

**Comment by cloud-yu** [comment]
need a configuration supporting Backspace sends ^H.

**Comment by tmalaher** [comment]
I agree with @cloud-yu 

For example: putty has a setting allowing you to choose whether the backspace key sends DEL (`0x7f`) or Backspace (^H `0x08`)

Version: 1.0.187
Platform: Windows x64 10.0.19044
Plugins: workspace-manager, theme-windows10, theme-hype, theme-gruvbox, save-output, relaxed-theme, quick-restart, quick-cmds, clippy
Frontend: xterm-webgl

**Comment by TanY0Y0** [comment]
> I agree with @cloud-yu
> 
> For example: putty has a setting allowing you to choose whether the backspace key sends DEL (`0x7f`) or Backspace (^H `0x08`)
> 
> Version: 1.0.187 Platform: Windows x64 10.0.19044 Plugins: workspace-manager, theme-windows10, theme-hype, theme-gruvbox, save-output, relaxed-theme, quick-restart, quick-cmds, clippy Frontend: xterm-webgl

so where is the setting to choose backspace key？I cant find it

**Comment by ray73864** [comment]
> so where is the setting to choose backspace key？I cant find it

I'm patiently waiting for this open too.

For most things I do in the terminal, backspace and delete work just fine, but 1 editor that I have to use for work, when I press 'delete', it puts a '~' in, and when I press 'backspace', it deletes the letter to the right not the left.

In MobaXterm, I can press 'backspace' to delete the letter to the left, and if I press 'shift+backspace' or 'ctrl+backspace' it will delete the letter to the right.

Really hoping re-mapping backspace to ^H like you can in Putty, etc... becomes a thing.

Otherwise, this has allowed me to move off of both MobaXterm and CryptoTerm (it does a better job than MobaXterm in pretty much everything except ^H support for backspace, and it does a better job than CryptoTerm for WYSE60 stuff).

**Comment by terral001** [comment]
when telnet to switch/router   the 'backspace' can't  delete any,  i must use ctr+H    ,how to use backspace as usual?

**Comment by Java-q** [comment]
Temporary solutions
1、Use Ctrl-H to go backward
2, use the left cursor key to move forward, and then Backspace to automatically delete backward

Hope to improve this problem

**Comment by Eugeny** [comment]
The new nightly will be ready soon - https://github.com/Eugeny/tabby/actions/runs/5561717712 - you'll find the new backspace setting on the Input tab of your profile config.

**Comment by Jiemin17** [comment]
> The new nightly will be ready soon - https://github.com/Eugeny/tabby/actions/runs/5561717712 - you'll find the new backspace setting on the Input tab of your profile config.
> 
> > <img alt="" width="48" src="https://repository-images.githubusercontent.com/77213120/49dde400-c8c2-11e9-812a-e1407f1f42af"><img alt="" height="14" src="https://camo.githubusercontent.com/b6a12909f1e31185a69a73d59208c507a992236d3230f9fc18e85058ae3d19e7/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e732f66617669636f6e2e737667"> GitHub**[fixed #5862 - configurable Backspace behaviour · Eugeny/tabby@fcac52a](https://github.com/Eugeny/tabby)**A terminal for a more modern age. Contribute to Eugeny/tabby development by creating an account on GitHub.

it works
thank you!
