### ISSUE TITLE
Making zmodem file transfers supports tmux.

### ISSUE THREAD

**Issue by lonnywong** [Eugeny/tabby#5928]
Zmodem ( rz / sz ) is not compatible with tmux.

I make a new file transfer tools [trzsz](https://github.com/trzsz/trzsz) ( trz / tsz ), similar to lrzsz ( rz / sz ), and compatible with tmux.

Trzsz ( trz / tsz ) supports iTerm2, just for MacOS users.

And, I make [trzsz.js](https://github.com/trzsz/trzsz.js) for cross-platform terminal apps.

I think tabby can support trzsz. Maybe as a plugin?

Maybe I can write the plugin myself. But, I'm not familiar with tabby.
How to filter the input and output of the server?
Could the plugin access the file system by `require('fs')`? 
Could the plugin open electron dialog?

**Comment by Eugeny** [comment]
Hey, great work! Yes, plugins can interact with the built-in upload/download manager without having to `require('fs')`. This will even work in Tabby Web. Check out how the actual Zmodem transfers are implemented: https://github.com/Eugeny/tabby/blob/master/tabby-terminal/src/features/zmodem.ts

Also, I to am working on a better file transfer spec here: https://github.com/shift-protocol/spec - which supports directory transfers and is transparent to terminal multiplexers. Would appreciate any feedback!

**Comment by lonnywong** [comment]
Thanks. I'm trying to make the trzsz plugin. https://github.com/trzsz/tabby-trzsz

After I installed the [tabby-trzsz](https://www.npmjs.com/package/tabby-trzsz) plugin, tabby restart fails, same as https://github.com/Eugeny/tabby/issues/4916 .

The tabby version is `1.0.173.0`.

**Comment by Eugeny** [comment]
It's possible that an exception is swallowed somewhere during plugin initialization. You can add "--inspect-brk" to the Tabby command line, and then you'll be able to debug the main process through the NodeJS inspector, e.g. by opening chrome://inspect in your local Chrome.

**Comment by lonnywong** [comment]
Oh, run with `--debug`, There are some error in the console.
```js
ERROR TypeError: Class constructor ToolbarButtonProvider cannot be invoked without 'new'
    at new MyButtonProvider
```
```js
    function MyButtonProvider() {
        return _super !== null && _super.apply(this, arguments) || this;
    }
```

Maybe I didn't build the example right.
https://github.com/Eugeny/tabby/blob/master/HACKING.md
```js
import { NgModule, Injectable } from '@angular/core'
import { ToolbarButtonProvider, ToolbarButton } from 'tabby-core'

@Injectable()
export class MyButtonProvider extends ToolbarButtonProvider {
    provide (): ToolbarButton[] {
        return [{
            icon: 'star',
            title: 'Foobar',
            weight: 10,
            click: () => {
                alert('Woohoo!')
            }
        }]
    }
}

@NgModule({
    providers: [
        { provide: ToolbarButtonProvider, useClass: MyButtonProvider, multi: true },
    ],
})
export default class MyModule { }
```

**Comment by Eugeny** [comment]
You're transpiling classes into function - since you didn't set the "target" in tsconfig.json it's compiling into es6 (IIRC). Check out to config.json from the sample plugin (tabby-clippy)

**Comment by lonnywong** [comment]
> You're transpiling classes into function - since you didn't set the "target" in tsconfig.json it's compiling into es6 (IIRC). Check out tsconfig.json that's used in the sample plugin (tabby-clippy), it's using target: es2016

Thanks @Eugeny , you saved me a lot of time.

After I published a new version, how long will it take to be updated? Seems like tabby always shows the old version.

**Comment by Eugeny** [comment]
Have you tried restarting Tabby already? It's pulling fresh info from NPM when you open the Plugins tab for the first time.

**Comment by lonnywong** [comment]
Yes, I restart tabby several times, and always shows the old version.

**Comment by lonnywong** [comment]
I reboot my computer, and it's still shows the old version. I try to install the plugin, it downloads the `0.1.0` version.

https://www.npmjs.com/package/tabby-trzsz is `0.1.1` 35 minutes ago.

**Comment by lonnywong** [comment]
It's works now after restart. Maybe we need to wait a few hours.

**Comment by lonnywong** [comment]
@Eugeny Please help. Thanks.

1. How to disable showing the server output temporary? `terminal.enablePassthrough = false` seems not working.
2. How to disable the user input while there are files transferring?
3. Can you help me review the code? https://github.com/trzsz/tabby-trzsz/blob/main/src/decorator.ts
    It works except the server output and user input. Am I doing `subscribeUntilDetached` right?

**Comment by Eugeny** [comment]
1. Are you sure this condition (https://github.com/trzsz/tabby-trzsz/blob/main/src/decorator.ts#L20) is correct? When `passthrough` is off, you're still writing the output to the terminal yourself.
2. This is not possible with just a decorator, but your can write a _Middleware_ that has complete control over the session data in both directions.

Create a subclass of [SessionMiddleware](https://docs.tabby.sh/terminal/classes/SessionMiddleware.html), override its [feedFromTerminal](https://github.com/Eugeny/tabby/blob/master/tabby-terminal/src/api/middleware.ts#L15) method, and push an instance of the middleware onto the [stack](https://docs.tabby.sh/terminal/classes/BaseSession.html#middleware).
You can also move the Trzsz logic itself into the middleware as well and only keep attach/detach logic in the decorator.

3. You should move all your `subscribeUntilDetached` calls (except `terminal.sessionChanged$` which should be _permanently_ subscribed) into `attachToSession` - otherwise the plugin will stop working when the active session in the tab changes (e.g. after an SSH reconnect). See how it's done in [zmodem](https://github.com/Eugeny/tabby/blob/master/tabby-terminal/src/features/zmodem.ts#L48-L53). The code looks good otherwise :+1:

**Comment by lonnywong** [comment]
Thanks for your help.
1. I write a text progress bar to the terminal while `passthrough` is off.
2. Let me try to use `SessionMiddleware`.
3. Is `terminal.resize$` not related to a session? Same as the `cancelEvent`. I'm a little confused.

**Comment by Eugeny** [comment]
1. I've found the problem! It was due to incorrect handling in the actual _zmodem_ decorator - it was relying on `enablePassthrough` instead of having its own "active" state - fixed in https://github.com/Eugeny/tabby/commit/780691413d6ec0fa82c591e51c2355d89d33e7dc - new build coming in https://github.com/Eugeny/tabby/actions/runs/2008672903
3. Sorry - ignore that - you're correct to subscribe to non-session events in `attach()`

**Comment by lonnywong** [comment]
Can I just push a `SessionMiddleware` without remove? 

Please help me review the code:
https://github.com/trzsz/tabby-trzsz/tree/main/src

It works, but I don't know if there will be an issue in some cases.

**Comment by Eugeny** [comment]
Yes - looks great! :+1: You don't need to remove the middleware because decorators never get detached until the tab is closed.

**Comment by lonnywong** [comment]
@Eugeny Thank you again for helping me.

**Comment by lonnywong** [comment]
It works. https://github.com/trzsz/tabby-trzsz
