### ISSUE TITLE
Remember Vault password

### ISSUE THREAD

**Issue by meyverick** [Eugeny/tabby#6344]
**Is your feature request related to a problem? Please describe.**
Tabby ask for my vault password every time I start it, without taking the `Remember for 7 Days` into account.

**Describe the solution you'd like**
Remember the vault password for 7 days, even if I close Tabby and shutdown the computer.

**Describe alternatives you've considered**
Perhaps forcing to enter the vault password after every computer start then take the `Remember...` choice into account.

**Comment by Eugeny** [comment]
If Tabby would remember the Vault password somewhere while the app is closed - i.e. not just in RAM, that would render Vault completely useless as you could just obtain the password from disk and decrypt it.

**Comment by SynapseScribe** [comment]
not if using windows hello

**Comment by TooMuhtsh** [comment]
For anyone landing here from a search: I built a plugin that addresses exactly this, while answering the objection above — the passphrase is never written to disk in a readable form. tabby-better-vault stores a token encrypted by the OS keychain (DPAPI on Windows — bound to your user session — Secret Service on Linux), and on Linux it refuses to activate on the insecure basic_text backend rather than pretend. Opt-in, automatic fallback to the native prompt. On npm as tabby-better-vault.
