### ISSUE TITLE
Fail to build with NodeJS v14.17.6 on Windows 10

### ISSUE THREAD

**Issue by joaompinto** [Eugeny/tabby#6589]
**Describe the problem**:
Following the HACKING.md instructions I am unable to build on Windows 10

**To Reproduce**:
Install NodeJS v14.17.6 on Windows 10
Run "yarn":

Fails with the following error:

```
C:\Users\lameg\tabby\scripts\build-native.js:9
    process.env.ARCH ??= process.arch
                     ^^^

SyntaxError: Unexpected token '??='
    at wrapSafe (internal/modules/cjs/loader.js:988:16)
    at Module._compile (internal/modules/cjs/loader.js:1036:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

```

**Comment by bdr99** [comment]
It seems that in https://github.com/Eugeny/tabby/commit/4a822947418acdbc010e909205e05657740e7079, `scripts/build-native.js` was updated to use [logical nullish assignment](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_nullish_assignment), which is a JS language feature only supported in Node.js 15 or higher. `HACKING.md` should be updated to indicate that Node.js 15 or higher is required.

@joaompinto For now, you might want to try updating to Node.js 16 since that is the current LTS release.

**Comment by joaompinto** [comment]
Submitted https://github.com/Eugeny/tabby/pull/6668 to close this.
