### ISSUE TITLE
git autocomplete

### ISSUE THREAD

**Issue by hailin84** [Eugeny/tabby#7012]
Could you guys consider to add git autocomplete feature? That'd be very helpful.

Auto complete for git commands, remote repo names, branch&tag names, etc. Just like cmder does.

**Comment by Eugeny** [comment]
With rare exceptions, terminal apps do not provide autocompletion. Consider something like https://github.com/marlonrichert/zsh-autocomplete

**Comment by Ama1999** [comment]
This is not a good idea, not just because terminals don't usually provide autocomplete, but also because autocompletion tends to be heavily dependent on user preference, so hardcoding a certain, specific kind of autocompletion may backfire for other users wanting to opt for another autocompletion script/protocol.

**Comment by hailin84** [comment]
OK, thanks. Maybe that's the duty of some plugins.
