### ISSUE TITLE
telnet to switch or console to terminal cannot use Backspace key

### ISSUE THREAD

**Issue by cmmchina** [Eugeny/tabby#7148]
终端连接到交换机后不能使用Backspace按键，还有部分乱码
<img width="501" alt="QQ20220921-103624@2x" src="https://user-images.githubusercontent.com/29941503/191406327-41c0c2b3-5d9b-4a2c-a7a5-905ba92f4d7d.png">

Version: 1.0.183
Platform: macOS arm64 21.6.0
Plugins: save-output, plugin-fig-integration, cloud-settings-sync
Frontend: xterm

**Comment by mikesrus** [comment]
This is a common problem when working with various switches from many manufacturers.

popular and telnet clients have an option to fix this situation
For example , 

- MobaXterm has option is called: "Backspace sends CTRL-H".
- putty configuration > Terminal > Keyboard > change sequences sent using -> backspace keys and change CTRL-? on CTRL-H.

it would be great to get such an option here. Because telnet is used in most cases to manage and configure network devices
