### ISSUE TITLE
Dropdown window breaks when multiple instances open

### ISSUE THREAD

**Issue by MatthewScholefield** [Eugeny/tabby#7162]
**Describe the problem**:

When the dropdown terminal mode is enabled and you open Tabby a second time (ie. accidentally), the dropdown terminal can no longer be opened and you need to kill all tabby processes. When clicking the hotkey button I see the dropdown terminal momentarily flash as if it opens and then immediately closes.

**To Reproduce**:

 - Enable dropdown terminal via hotkey
 - Ensure Tabby is running (ie. the first instance). Verify the hotkey works
 - Start Tabby again (second instance). The hotkey should no longer open the dropdown

**Details:**

 - Platform: Windows 11
 - Version: 1.0.183 (latest as of now)

**Comment by Drakal** [comment]
I can confirm this still occurs in 1.0.196 as well on Windows 10 LTSC 2021. A workaround is to disable "Hide window on focus loss" under Window>Docking. Not elegant since clicking away is convenient but at least doesn't put Tabby in an unusable state if, like me, you added it to Win+X and forget that if it was already running but hidden.

Once this option was disabled I saw when launching Tabby again, it opens a new window rather than another tab, and that may be the issue.

This is speculation but when trying to show Tabby with ^Space, perhaps it's a race condition where one window gets the signal first and when the second window gets focus, the first loses it, triggering the "hide on lost focus" feature for all of them?
