### ISSUE TITLE
tabby no response when search text

### ISSUE THREAD

**Issue by lovesharepc** [Eugeny/tabby#7579]
**Describe the problem**:
tabby no response when search text 

**To Reproduce**:
my config scrollback  setting is 40000

when new windows start
search feature is work

bug when a while, there is many line in buffer 
search text will cause tabby no response
when I use top view usage 
tabby is going 100% 

tabby version: v1.0.187
OS: xubuntu 22.04

in tabby version:  v1.0.186 is no this problem

**Comment by enodr** [comment]
I confirm this is a real issue. The problem seems the lack of key debouncing. If you start typing one char in the search box it will immediatly search for that only char in the whole scrollback thus using lot of CPU. Having some sort of key debouncing while the user is typing would maybe improve performance and usability?
