### ISSUE TITLE
When connection is lost, history gets deleted.

### ISSUE THREAD

**Issue by urbels** [Eugeny/tabby#8294]
I have a weird issue with connection not related to tabby, but whats related to tabby is - history gets lost. Every time I lose connection and tabby shows "reconnecting" history gets deleted.

**Comment by K-TheMartian** [comment]
This is not related to Tabby, this is the behavior in all ssh terminals due to the bash history mechanics.
When the connection is terminated (for any reason), the history is not saved,
the session must be closed properly, so all commands are dumped into the history file.
I hope maybe there could be a mechanism where all the commands are saved within tabby and if reconnected it populates back the bash history file.

**Comment by urbels** [comment]
> Check in settings SSH > "Clear terminal after connection"

Thank you! That fixed it for me. No idea when it was itroduced because before it was fine.

**Comment by Spoilt** [comment]
Sorry to dig up this thread, but the option doesn't seem to be there any more. Is it still available?
