### ISSUE TITLE
It's lagging.

### ISSUE THREAD

**Issue by Amaderis** [Eugeny/tabby#9378]
Terrible lag when typing on the server. But in another SSH client (MobaXterm) everything is smooth and without such delays. It is impossible to work on data center nodes at all. I really like this application, better than MobaXterm. But this problem is very stressful. 

Version: 1.0.205
Platform: Windows x64 10.0.22631
Plugins: none
Frontend: xterm-webgl

**Comment by atlas-eric** [comment]
V1.0.205
The large prompt lag on my new installed M2-Mac
One tab open only

Makes it barely useable.

**Comment by gitmatters** [comment]
Use version 1.0.198 . It's the last version, where ssh and x11 forwarding working flawlessly.

**Comment by element0xE** [comment]
> Use version 1.0.197 . It's the last version, where ssh and x11 forwarding working flawlessly.

I can confirm the typing expirience tru SSH is flawless with version 1.0.197
MacOS Sonoma 14.3.1 | M2 Max

**Comment by atlas-eric** [comment]
Correct.
I went back too and it works great. Sonoma both Intel and M2 versions

**Comment by Eugeny** [comment]
Could you please [record a performance trace](https://developer.chrome.com/docs/devtools/performance/reference#record-runtime) on the new version using the built-in debug tools?

**Comment by atlas-eric** [comment]
How do I connect the Tabby app to the Chrome Dev Tools, for that
performance trace?

**Comment by Eugeny** [comment]
Tabby has them built in, it's in Settings -> Application -> Debugging

**Comment by Eugeny** [comment]
That's weird - it works for me via the toolbar button:

<img width="306" alt="Screenshot 2024-03-11 at 21 19 03" src="https://github.com/Eugeny/tabby/assets/161476/2f694961-d441-4406-a5d7-86038267e07f">

**Comment by Eziou** [comment]
Same, v1.0.207 and severe lag on my new m3 pro macbook, macos Sonoma 14.4.

**Comment by element0xE** [comment]
> That's weird - it works for me via the toolbar button:
> 
> <img alt="Screenshot 2024-03-11 at 21 19 03" width="306" src="https://private-user-images.githubusercontent.com/161476/311855503-2f694961-d441-4406-a5d7-86038267e07f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzMzg5MzQsIm5iZiI6MTcxMDMzODYzNCwicGF0aCI6Ii8xNjE0NzYvMzExODU1NTAzLTJmNjk0OTYxLWQ0NDEtNDQwNi1hNWQ3LTg2MDM4MjY3ZTA3Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxM1QxNDAzNTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lOTBiODdiYjg5ZWZjMmJlZjMwODA5YzUyMjMyYjcwNTgwYWRlYTUwYWRmNmFjZDMzZDg0ODI1NTMzNzk5MDNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.uNAvICuf0FbCLjNT9YTuAgrR6DyThCag3Kp-1iuxqSI">

I have attempted to save the performance profile multiple times.
When I start recording the profile on a local terminal, the save dialog appears correctly, but when I click 'Save', the following error is printed in the console: [insert error message here]. This results in a 0 byte saved file.
`[2728:0313/182625.971232:ERROR:CONSOLE(1)] "Error: The request is not allowed by the user agent or the platform in the current context.", source: devtools://devtools/bundled/panels/timeline/timeline.js (1)`
![image](https://github.com/Eugeny/tabby/assets/15672402/8bfc6cdb-ea7d-4dc6-a5bd-cc8dad3dfbb3)
****
If I try to record the profile during an SSH session the **Save** dialog does not appear as expected.
Let me know if you need more specific screenshot maybe can be usefuel.

**Comment by atlas-eric** [comment]
Hi Mattia,
Thanks so much for your follow up. Eric is away on holiday and will get
back to you next week. Until then, be well!
Matt

**Comment by sterid** [comment]
> Any update on this issue ? People are still opening new issues about it , I think SSH connection is one of the core features of Tabby and we should focus on it.

totally agree

**Comment by fhackenberger** [comment]
Same issues with 1.0.207 on Ubuntu 23.10. Version 1.0.197 works nicely without any lagging. I'm also unable to save a performance trace unfortunately.

**Comment by bristlehog** [comment]
Same issue for me with Tabby 1.0.207 for Windows 11 Home, but it lags only when working through SSH, while the local terminal doesn't lag. There's a noticeable lag between every keypress and the letter actually appearing on the screen.

I've tried to do a performance profile, but couldn't save it - the save button just does nothing. Attaching the profile screenshot - there are some dropped frames, but not sure if they're to blame or not.

![tabby_perf_profile](https://github.com/Eugeny/tabby/assets/10199661/dd6ea3ea-8fad-4e74-a525-5cd8c217b6ab)

**Comment by Vadhvis** [comment]
Same issue here.
Windows 11 22H2, Ryzen 5800X, RTX 2070

I did some testing and only keyboard input via ssh seems to be lagging. Local shell works perfectly fine.
Htop with low delay seems not to be skipping frames either.

More specifically I tested alpha 208, 198 and 197.
(Input) lag seem present on both 208 and 198, but not on 197.
Coincidentially, profile saving does not work on both 208 and 198. On 208 nothing happens when pressing the save button, on 198 the following error gets presented in console
`Failed to save timeline: The request is not allowed by the user agent or the platform in the current context. (NotAllowedError)`
Profile saving works fine on 197.

Having had a look at the profile themselves I'm not sure where the lagging comes from. On 208 there are some long dropped frames present but I couldn't reproduce them 198.
There are some Partially Presented Frames on 198 but those are present also on 197, so they do not seem related to the issue.

**Comment by Vadhvis** [comment]
Problem seems to be related to newer ssh2 package versions.
I managed to build Alpha 208 with the old ssh2 used in Alpha 197 (`Eugeny/ssh2#9de907d62907d6d45debdcc0ed8dda5b7b19dc7c`, seems to be a slightly modified version of ssh2 1.11) and it works perfectly fine without any lag

Now I'm no ssh expert, but in case anyone would want to have a look at what could be the cause here's the comparison of the two versions
https://github.com/mscdex/ssh2/compare/24b497ddf2d727ecf3e3e6d414a5ba6172fe320f...v1.14.0

**Comment by gitmatters** [comment]
@mscdex can you have a look at what @Vadhvis found out. It seems like there is an issue with ssh2 version 1.12+, which causes major constraints for Tabby.

**Comment by mscdex** [comment]
Try adding `client.setNoDelay(true);` once connected. Other than that, I have no suggestions.

**Comment by Vadhvis** [comment]
> Try adding `client.setNoDelay(true);` once connected. Other than that, I have no suggestions.

Worked like a charm, thanks.
I'll prepare a PR tomorrow

**Comment by atlasstaking** [comment]
Thanks for all the hard work!!
Great news!
