### ISSUE TITLE
SSH problems? Try this experimental build

### ISSUE THREAD

**Issue by Eugeny** [Eugeny/tabby#9810]
If you're having issues with SSH authorization, performance or connecting to specific hosts, try out this experimental branch:

👉 https://nightly.link/Eugeny/tabby/workflows/build/russh 👈 

It includes a new experimental SSH backend based on [russh](https://github.com/eugeny/russh)

This build has all the features of the stable Tabby' SSH client!

New stuff available only in that build:
* chacha20-poly1305 cipher
* 3DES-CBC cipher (for old Cisco hardware)
* remembering answers to password prompts in keyboard-interactive auth

I would appreciate any feedback on that build, even just a comment if everything works fine!

**Comment by Clem-Fern** [comment]
After a week using this build, a list of issues I got:

- I can't connect to server using private key anymore. The passphrase prompt is not displayed.
```
SSH  Loading private key: file:///home/clem/.ssh/my_private_key
SSH   !  Failed to load private key file:///home/clem/.ssh/my_private_key: Error: Keys(KeyIsEncrypted)
```
From debug console
```
21:43:41.019 /opt/Tabby/resources/builtin-plugins/tabby-core/dist/index.js:15841 [ssh-x.x.x.x] Loading private key: file:///home/clem/.ssh/id_X
21:43:41.021 /opt/Tabby/resources/builtin-plugins/tabby-core/dist/index.js:15841 [ssh--x.x.x.x]  !  Failed to load private key file:///home/clem/.ssh/id_X: Error: Keys(KeyIsEncrypted)
```

- Tabby does not detect when sessions are disconnected.

- ~~Output is pretty slow and jerky when using commands like more, tail, show logs.~~ Same problem with the latest release. So not related to this build. Sadly, I can't save performance profile because of a bug...

**Comment by Eugeny** [comment]
Saving performance traces is now fixed in the latest nightly: [nightly.link/Eugeny/tabby/workflows/build/master](https://nightly.link/Eugeny/tabby/workflows/build/master)

**Comment by ozairakhlaq** [comment]
Hi, I have a similar problem with Cisco devices when using the latest build. Came across this while searching. When will this be released as stable?

**Comment by Eugeny** [comment]
Hopefully soon, I still need to test it more

**Comment by Clem-Fern** [comment]
I'm using this build for one month now. Working fine for me.

Have you change anything which could help with performance issues (slow output) ? It seems better with the latest build. I can't say for sure, it was a bit random.

**Comment by Eugeny** [comment]
I haven't changed anything significant, but you should now be able to save a performance trace since that's fixed.

**Comment by Clem-Fern** [comment]
> I haven't changed anything significant, but you should now be able to save a performance trace since that's fixed.

Great ! I'll keep you update if i have issues again.

**Comment by peix187** [comment]
Hi,

I have a problem with the last build v1.0.211 and this release. The user set in the  **.ssh\config** is not used.
I use the ssh config file **C:\Users\xxx\.ssh\config** on **Windows 11 23H2 22631.4037**.

```
Host srv-a
    Hostname 172.22.0.1

Host srv-*
    User admin
    IdentitiesOnly yes
    IdentityFile ~/.ssh/mysshkey
```
When i select the profile **srv-a** imported from **.ssh\config** the user is not **admin** but **root** (i see this on the top of the screen root@172.22.0.1:22).
On a new terminal in Tabby, if i run **ssh srv-a** the user used is **admin**.
The problem seems to be located on the parsed elements because when i add **User admin** in the section of **srv-a** the user used is good.

**Comment by Eugeny** [comment]
russh backend is now included in the normal nightly build
